apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: jayde-quiz-backstage
  description: Find where your juice comes from
spec:
  type: website
  lifecycle: production
  owner: tracking-team
